core/blog/api/v1/urls.py
from django.urls import path , include
from .views import *
from rest_framework.routers import *
"""Using DefaultRouter to generate paths for views"""
router = DefaultRouter()
router.register('post',PostModelViewSet, basename='post')
router.register('category',CategoryModelViewSet, basename='category')
app_name = 'api-v1'
# urlpatterns = [
    # paths to function based views
    # path('post/<int:id>/', postDetail,name='post-detail'),
    # path('post/', postList,name='post-list'),
    # paths to class based views
    # path('post/', PostList.as_view(),name='post-list'),
    # path('post/<int:pk>/', PostDetail.as_view(),name='post-detail'),
    # paths to GenericViewSet views
    # path('post/', PostViewSet.as_view({'get':'list','post':'create'}), name='post-list'),
    # path('post/<int:pk>', PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), name='post-detail')
#]
urlpatterns = router.urls

core/blog/urls.py
from django.urls import path , include
from django.views.generic import *
from .views import *
app_name = 'blog'
urlpatterns = [
    # Main url
    path('', redirect_main, name='redirect'),
    # Urls to class based view in views.py
    path('post/', PostListView.as_view(),name='post-list'),
    path('post/<int:pk>/' , PostDetailView.as_view(), name="post-detail"),
    path('post/create', PostCreateView.as_view(), name='post-create'),    
    path('post/<int:pk>/edit/', PostEditView.as_view(), name='post-edit'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    # A path to include paths in api/v1/urls.py 
    path('api/v1/', include('blog.api.v1.urls'),name='api-v1'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi 
schema_view = get_schema_view(
   openapi.Info(
      title="Blog API",
      default_version='v1',
      description="advanced blog",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="arshiasheikhbahayi@gmail.com"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-docs/', include_docs_urls(title='api-simple')),
    path('swagger/output.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]


  

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import *
from django.urls import reverse
# Create your models here.

"""A model using in blog app. contains different parts and works like a twit """
class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()
    def __str__(self):
        return self.title
    def get_snippet(self):
       return self.content[0:5]
    def get_absolute_api_url(self):
       return reverse("blog:api-v1:post-detail", kwargs={"pk":self.pk})

"""A model that just have a name. It is used with a many-to-many relationship to category part in post model"""
class Category(models.Model):
  name = models.CharField(max_length=255)
  def __str__(self):
    return self.name

core/blog/forms.py
from django import forms
from .models import Post
"""A class that inherits from model post (in models.py) and have the same field (except some) to create a object post"""
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'status', 'category', 'published_date']

core/blog/api/v1/views.py
from rest_framework.decorators import *
from rest_framework.permissions import *
from rest_framework.response import *
from rest_framework import viewsets
from rest_framework.views import *
from rest_framework.generics import *
from blog.models import *
from .serializers import *
from django.shortcuts import get_object_or_404
from .permissions import *
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter , OrderingFilter
from .paginations import *
# Example of function based view for api
"""An function based api view that allows the user to get a list of all objects of post model and also creating a new one"""
'''@api_view(["GET", "POST"])
@permission_classes([IsAuthenticated])
def postList(request):
    if request.method == "GET":
        posts = Post.objects.filter(status=True)
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)
    elif request.method == "POST":
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)'''
"""An function based api view that allows the user to get a certain object of post model and deleting it or editing it"""
'''@api_view(["GET", "PUT", "DELETE"])
def postDetail(request, id):
    post = get_object_or_404(Post, pk=id, status=True)
    if request.method == "GET":
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method == "PUT":
        serializer = PostSerializer(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == "DELETE":
        post.delete()
        return Response({"detail": "Item removed successfully"}, status=status.HTTP_204_NO_CONTENT)
'''

# Example of class based view for api
"""An class based view api that inherits from APIView and allows the user to get a certain object of post model and deleting it or editing it"""
'''class PostDetail(APIView):
    """ getting detail of a post and edit + delete """
    permission_classes = [IsAuthenticated]
    serializer_class = PostSerializer

    def get(self, request, id):
        """retrieving the post data"""
        post = get_object_or_404(Post, pk=id, status=True)
        serializer = self.serializer_class(post)
        return Response(serializer.data)

    def put(self, request, id):
        """editing the post data"""
        post = get_object_or_404(Post, pk=id, status=True)
        serializer = PostSerializer(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

    def delete(self, request, id):
        """deleting a post"""
        post = get_object_or_404(Post, pk=id, status=True)
        post.delete()
        return Response({"detail": "Item removed successfully"}, status=status.HTTP_204_NO_CONTENT)
'''
"""An class based view api that inherits from APIView and allows the user to get a list of all objects of post model and also creating a new one"""
'''class PostList(APIView):
    """getting a list of posts and creating new post"""
    permission_classes = [IsAuthenticated]
    serializer_class = PostSerializer
    def get(self, request):
        """retrieving a list of posts """
        posts = Post.objects.filter(status=True)
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    def post(self, request):
        """creating a post with provided data"""
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
'''

# Example of generic api views
"""An class based api view that inherits from ListCreateAPIView and allows the user to get a list of all objects of post model and also creating a new one"""
'''class PostList(ListCreateAPIView):
    """getting a list of posts and creating new post"""
    permission_classes = [IsAuthenticated]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)'''
"""An class based api view that inherits from RetrieveUpdateDestroyAPIView and allows the user to get a certain object of post model and deleting it or editing it"""
'''class PostDetail(RetrieveUpdateDestroyAPIView):
    """getting a special post by its id and editing it or deleting it"""
    permission_classes = [IsAuthenticated]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)'''

#Example of ModelViewSet api views
class PostModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend,SearchFilter,OrderingFilter]
    filterset_fields = {'category':["exact","in"],'author':["exact"],'title':["exact"]}
    search_fields = ['title','content']
    ordering_fields = ['published_date']
    # pagination_class = pagination
class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import *
from .models import *
from .forms import *
from django.contrib.auth.mixins import *
from rest_framework.decorators import *
from rest_framework.response import Response
# Create your views here.
"""A function based view to redirect users to post-list with ('post/) url """
def redirect_main(request):
    return redirect('accounts/api/v1/registration/')

"""A class based view inheriting from Django Generic Views (ListView) to show a list of objects of model post """    
class PostListView(PermissionRequiredMixin,LoginRequiredMixin,ListView):
    permission_required = 'blog.view_post'
    queryset = Post.objects.filter(status=1)
    context_object_name = 'posts'
    paginate_by = 1
    ordering = '-created_date'

"""A class based view inheriting from Django Generic Views (DetailVIew) to show details of an object of a models by Pk"""
class PostDetailView(LoginRequiredMixin,DetailView):
    model = Post

"""A class based view inheriting from Django Generic Views (CreateView) to show a form for creating a object of a model and creating it"""
class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    form_class = PostForm
    success_url = '/blog/post'
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

"""A class based view inheriting from Django Generic Views (UpdateView) to show a filled form for updating a model"""    
class PostEditView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    success_url = '/blog/post/'

"""A class based view inheriting from Django Generic Views (DeleteView) to delete a object of a model"""
class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = '/blog/post'

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #error_message {
            position: absolute;
            top: 330px;
            left: 400px;
            font-size: xx-large;
            color: red;
        }

        #delete_message {
            color: red;
            font-size: medium;
        }
    </style>
</head>

<body>
    {% if request.user == object.author %}
    <form method="post">{% csrf_token %}
        <p id="delete_message">Are you sure you want to delete "{{object}}" ?</p>
        <input type="submit" value="Confirm">
        <button ><a href="{% url 'blog:post-detail' pk=post.id %}">Cancel</a></button>
    </form>
    {% else %}
    <p id="error_message">you are not the author of this post so you can not delete it</p>
    {% endif %}
</body>

</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{post.title}}</title>
    <style>
        #Delete {
            position: absolute;
            top: 600px;
            left: 1470px;
        }
        #logged {
                position: absolute;
                right: 10px;
                top: 0px;
                color: dimgrey;
                font-size: 0.5cm;
        }
        
    </style>
</head>

<body>
    <h3 id="logged">logged in as {{request.user}}</h3>
    <h1>{{object.title}}</h1>
    {% if request.user == post.author %}
    <a href="{% url 'blog:post-edit' pk=post.id %}">
        <h5>Edit</h5>
    </a>
    {% endif %}
    <hr>
    <small>{{object.author.first_name}} - {{object.published_date}}</small><br>
    {% if request.user == post.author %}
    <a id="Delete" href="{% url 'blog:post-delete' pk=post.id %}">Delete</a>
    {% endif %}
    <p>{{object.content}}</p>
    <a href="{% url 'blog:post-list' %}">back to main blog page</a>

</body>

</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form method="post">{% csrf_token %}
       {{form.as_p}}
       <input type="submit" value="Save">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #logged {
            position: absolute;
            right: 10px;
            top: 0px;
            color: dimgrey;
            font-size: 0.5cm;
        }
    </style>
</head>

<body>
    <h3 id="logged">logged in as {{request.user}}</h3>
    <h1>blog posts</h1>
    {% for post in posts %}
    <div>
        <a href="{% url 'blog:post-detail' pk=post.id %}">
            <h2>{{post.id}}.{{post.title}}</h2>
        </a>

        <p>{{post.content}} - {{post.published_date}}</p>
        {% if post.image %}
        <img src="{{post.image.url}}" alt="">
        {% endif %}
        {{post.author}}
    </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            <a href="{% url 'blog:post-create' %}">create post</a>
        </span>
    </div>
</body>

</html>